services:
  apache-web:
    image: httpd:2.4-alpine
    container_name: shaka-website-apache
    ports:
      - "38080:80"
    volumes:
      # Monta la cartella website sulla root di Apache
      - ./app/website:/usr/local/apache2/htdocs
      # Monta le altre cartelle come sottocartelle
      - ./app/risorse:/usr/local/apache2/htdocs/risorse
      - ./app/template:/usr/local/apache2/htdocs/template
    restart: unless-stopped
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    networks:
      - shaka-website-network

networks:
  shaka-website-network:
    driver: bridge
